### ISSUE TITLE
Unable to link to capsule

### ISSUE THREAD

**Issue by WellsBit** [fuwn/capybara#2]
Hey! I'm trying to link to my my capsule on my website:

>=> gemini://jdj.golf Gemini

But obviously, this is will is being changed to https:
>=> https://jdj.golf Gemini

Perhaps a feature could be implemented to leave certain links unaffected? E. g:
`capybara -b localhost:8081 -s style.css **-u gemini://capsule.com** gemini://capsule.com`

**Comment by Fuwn** [comment]
Commit <https://github.com/gemrest/capybara/commit/5ddf4db7c4ed84fb041eaf066eec3cf3f7e73112> now allows you to specify a `capybara.keep_gemini` key within the new `Capybara.yaml` configuration file, the values of which will not be proxied.

I hope this remedies your situation, @WellsBit.

# Configuration Format
```yaml
capybara:
  keep_gemini: # A list of hosts where if the host is present; the URL will not be proxied
    - fuwn.me  #
               # Example:
               #   Proxied: `gemini://gem.rest` becomes `/proxy/gem.rest`
               #   Not proxied (present in `capybara.keep_gemini`): `gemini://gem.rest` is kept
```
